require 'echoe'

Echoe.new("samtools-ruby", version=0.1) do |p|
   p.author = "Ricardo H. Ramirez-Gonzalez"
   p.summary = "Binder of samtools for ruby, on the top of FFI. "
   p.url = "http://github.com/homonecloco/samtools-ruby"
end
 
 
desc "Basic test"
task :test do
  ruby "test/basictest.rb"
end